# Generated by Django 5.1.4 on 2026-06-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "0023_shopoffer_shopofferingredient_shopofferitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "premium_cost",
                    models.PositiveIntegerField(
                        verbose_name="Стоимость в премиум-валюте"
                    ),
                ),
                (
                    "money_copper_reward",
                    models.PositiveIntegerField(
                        verbose_name="Награда в медных монетах"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение обмена валюты",
                "verbose_name_plural": "Предложения обмена валюты",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PremiumCurrencyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("amount", models.IntegerField(verbose_name="Сумма (со знаком)")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("admin_grant", "Начисление администратором"),
                            ("shop_purchase", "Покупка в магазине"),
                            ("exchange_to_money", "Обмен на монеты"),
                            ("payment", "Оплата"),
                            ("refund", "Возврат"),
                        ],
                        max_length=64,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="Баланс после операции"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция премиум-валюты",
                "verbose_name_plural": "Транзакции премиум-валюты",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyExchangeTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "premium_spent",
                    models.PositiveIntegerField(
                        verbose_name="Потрачено премиум-валюты"
                    ),
                ),
                (
                    "money_copper_received",
                    models.PositiveIntegerField(verbose_name="Получено медных монет"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_exchange_transactions",
                        to="game.character",
                        verbose_name="Герой",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="billing.currencyexchangeoffer",
                        verbose_name="Предложение обмена",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_exchange_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "premium_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchange_transaction",
                        to="billing.premiumcurrencytransaction",
                        verbose_name="Транзакция премиум-валюты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция обмена валюты",
                "verbose_name_plural": "Транзакции обмена валюты",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserPremiumBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Баланс премиум-валюты"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_balance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баланс премиум-валюты",
                "verbose_name_plural": "Балансы премиум-валюты",
            },
        ),
    ]
