# Generated by Django 5.1.4 on 2026-06-10 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumTopUpOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "premium_amount",
                    models.PositiveIntegerField(
                        verbose_name="Количество премиум-валюты"
                    ),
                ),
                (
                    "price_amount_minor",
                    models.PositiveIntegerField(verbose_name="Цена в minor units"),
                ),
                (
                    "price_currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта цены"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет пополнения премиум-валюты",
                "verbose_name_plural": "Пакеты пополнения премиум-валюты",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PremiumTopUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "premium_amount",
                    models.PositiveIntegerField(
                        verbose_name="Снимок количества премиум-валюты"
                    ),
                ),
                (
                    "price_amount_minor",
                    models.PositiveIntegerField(
                        verbose_name="Снимок цены в minor units"
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Снимок валюты цены"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создано"),
                            ("pending", "Ожидает оплаты"),
                            ("succeeded", "Успешно"),
                            ("failed", "Неуспешно"),
                            ("canceled", "Отменено"),
                            ("expired", "Истекло"),
                            ("refunded", "Возвращено"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Провайдер"
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="ID платежа у провайдера",
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(blank=True, null=True, verbose_name="Checkout URL"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="ID возврата у провайдера",
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата возврата"
                    ),
                ),
                (
                    "premium_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="top_up",
                        to="billing.premiumcurrencytransaction",
                        verbose_name="Транзакция начисления премиум-валюты",
                    ),
                ),
                (
                    "refund_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunded_top_up",
                        to="billing.premiumcurrencytransaction",
                        verbose_name="Транзакция возврата премиум-валюты",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_top_ups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="top_ups",
                        to="billing.premiumtopupoffer",
                        verbose_name="Пакет пополнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пополнение премиум-валюты",
                "verbose_name_plural": "Пополнения премиум-валюты",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PremiumTopUpEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("provider", models.CharField(max_length=64, verbose_name="Провайдер")),
                (
                    "provider_event_id",
                    models.CharField(
                        max_length=128, verbose_name="ID события у провайдера"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=128, verbose_name="Тип события"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("processed", "Обработано"),
                            ("failed", "Ошибка"),
                            ("ignored", "Проигнорировано"),
                        ],
                        default="received",
                        max_length=32,
                        verbose_name="Статус обработки",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "top_up",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="billing.premiumtopup",
                        verbose_name="Пополнение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие пополнения премиум-валюты",
                "verbose_name_plural": "События пополнений премиум-валюты",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_event_id"),
                        name="billing_topupevent_unique_provider_event",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="premiumtopup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("user", "idempotency_key"),
                name="billing_topup_unique_user_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="premiumtopup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_payment_id__isnull", False)),
                fields=("provider", "provider_payment_id"),
                name="billing_topup_unique_provider_payment",
            ),
        ),
    ]
