from django.urls import path

from .views import (
    CharacterClassListView,
    CharacterCreateView,
    CharacterMeView,
    DungeonLocationLootView,
    DungeonMiniGameHistoryView,
    DungeonMiniGameMoveView,
    DungeonMiniGameRevealView,
    DungeonMiniGameStartView,
    MiniGameCardFaceCatalogView,
    MiniGameConfigCatalogView,
    DungeonLocationDetailView,
    DungeonLocationListView,
    DungeonRunClaimView,
    DungeonRunCurrentView,
    DungeonRunHistoryView,
    DungeonRunStartView,
    IconAssetsView,
    InventoryItemDetailView,
    InventoryItemEquipView,
    InventoryItemRepairPreviewView,
    InventoryItemRepairView,
    InventoryItemUnequipView,
    InventoryItemsDestroyPreviewView,
    InventoryItemsDestroyView,
    InventoryItemsRepairPreviewView,
    InventoryItemsRepairView,
    InventoryView,
    LeaderboardView,
    LoginView,
    LogoutView,
    MeView,
    PotionListView,
    PotionUseView,
    RegisterView,
    ThrottledTokenRefreshView,
    TotpLoginView,
    TwoFactorConfirmView,
    TwoFactorDisableView,
    TwoFactorSetupView,
    TwoFactorStatusView,
    UserAvatarUpdateView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view(), name="auth_register"),
    path("auth/login", LoginView.as_view(), name="auth_login"),
    path("auth/login/totp", TotpLoginView.as_view(), name="auth_login_totp"),
    path("auth/refresh", ThrottledTokenRefreshView.as_view(), name="auth_refresh"),
    path("auth/me", MeView.as_view(), name="auth_me"),
    path("auth/two-factor", TwoFactorStatusView.as_view(), name="auth_two_factor_status"),
    path("auth/two-factor/setup", TwoFactorSetupView.as_view(), name="auth_two_factor_setup"),
    path("auth/two-factor/confirm", TwoFactorConfirmView.as_view(), name="auth_two_factor_confirm"),
    path("auth/two-factor/disable", TwoFactorDisableView.as_view(), name="auth_two_factor_disable"),
    path("auth/logout", LogoutView.as_view(), name="auth_logout"),
    path("character-classes", CharacterClassListView.as_view(), name="character_classes"),
    path("characters", CharacterCreateView.as_view(), name="character_create"),
    path("characters/me", CharacterMeView.as_view(), name="character_me"),
    path("dungeons", DungeonLocationListView.as_view(), name="dungeon_list"),
    path("dungeons/<int:pk>", DungeonLocationDetailView.as_view(), name="dungeon_detail"),
    path("dungeons/<int:pk>/loot", DungeonLocationLootView.as_view(), name="dungeon_loot"),
    path("dungeon-runs", DungeonRunStartView.as_view(), name="dungeon_run_start"),
    path("dungeon-runs/current", DungeonRunCurrentView.as_view(), name="dungeon_run_current"),
    path("dungeon-runs/<int:pk>/claim", DungeonRunClaimView.as_view(), name="dungeon_run_claim"),
    path("dungeon-runs/<int:pk>/mini-game/start", DungeonMiniGameStartView.as_view(), name="dungeon_mini_game_start"),
    path("dungeon-mini-games/<int:pk>/reveal", DungeonMiniGameRevealView.as_view(), name="dungeon_mini_game_reveal"),
    path("dungeon-mini-games/<int:pk>/move", DungeonMiniGameMoveView.as_view(), name="dungeon_mini_game_move"),
    path("dungeon-mini-games/history", DungeonMiniGameHistoryView.as_view(), name="dungeon_mini_game_history"),
    path("mini-game/configs", MiniGameConfigCatalogView.as_view(), name="mini_game_configs"),
    path("mini-game/card-faces", MiniGameCardFaceCatalogView.as_view(), name="mini_game_card_faces"),
    path("dungeon-runs/history", DungeonRunHistoryView.as_view(), name="dungeon_run_history"),
    path("inventory", InventoryView.as_view(), name="inventory"),
    path("inventory/items/repair-preview", InventoryItemsRepairPreviewView.as_view(), name="inventory_items_repair_preview"),
    path("inventory/items/repair", InventoryItemsRepairView.as_view(), name="inventory_items_repair"),
    path("inventory/items/destroy-preview", InventoryItemsDestroyPreviewView.as_view(), name="inventory_items_destroy_preview"),
    path("inventory/items/destroy", InventoryItemsDestroyView.as_view(), name="inventory_items_destroy"),
    path("inventory/items/<int:item_id>", InventoryItemDetailView.as_view(), name="inventory_item_detail"),
    path("inventory/items/<int:item_id>/repair-preview", InventoryItemRepairPreviewView.as_view(), name="inventory_item_repair_preview"),
    path("inventory/items/<int:item_id>/repair", InventoryItemRepairView.as_view(), name="inventory_item_repair"),
    path("inventory/items/<int:item_id>/equip", InventoryItemEquipView.as_view(), name="inventory_item_equip"),
    path("inventory/items/<int:item_id>/unequip", InventoryItemUnequipView.as_view(), name="inventory_item_unequip"),
    path("potions", PotionListView.as_view(), name="potions"),
    path("potions/use", PotionUseView.as_view(), name="potions_use"),
    path("leaderboard", LeaderboardView.as_view(), name="leaderboard"),
    path("media/icons", IconAssetsView.as_view(), name="media_icons"),
    path("auth/me/avatar", UserAvatarUpdateView.as_view(), name="auth_me_avatar"),
]
