# Generated by Django 5.1.4 on 2026-05-16 14:44

import apps.game.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                ("key", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("start_health", models.PositiveIntegerField()),
                ("start_attack", models.PositiveIntegerField()),
                ("start_defense", models.PositiveIntegerField()),
                ("start_critical_chance", models.FloatField()),
                ("start_evasion", models.FloatField()),
                ("growth_profile", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DungeonLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("duration_seconds", models.PositiveIntegerField()),
                ("required_power", models.FloatField()),
                ("experience_min", models.PositiveIntegerField()),
                ("experience_max", models.PositiveIntegerField()),
                ("money_min_copper", models.PositiveIntegerField()),
                ("money_max_copper", models.PositiveIntegerField()),
                ("item_drop_chance", models.FloatField()),
                ("rarity_chances", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentSlotConfig",
            fields=[
                ("key", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="GameConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("helmet", "Helmet"),
                            ("armor", "Armor"),
                            ("boots", "Boots"),
                            ("ring", "Ring"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("sword", "Sword"),
                            ("dagger", "Dagger"),
                            ("staff", "Staff"),
                            ("bow", "Bow"),
                            ("helmet", "Helmet"),
                            ("armor", "Armor"),
                            ("boots", "Boots"),
                            ("ring", "Ring"),
                        ],
                        max_length=20,
                    ),
                ),
                ("allowed_classes", models.JSONField(blank=True, null=True)),
                ("possible_stats", models.JSONField(default=dict)),
                ("min_durability", models.PositiveIntegerField(default=10)),
                ("max_durability", models.PositiveIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["slot", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_url", models.URLField(blank=True, default="")),
                ("large_url", models.URLField(blank=True, default="")),
                ("medium_url", models.URLField(blank=True, default="")),
                ("small_url", models.URLField(blank=True, default="")),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                ("icon_url", models.URLField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RarityConfig",
            fields=[
                ("key", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("stat_multiplier", models.FloatField()),
                ("min_item_level", models.PositiveIntegerField()),
                ("max_item_level", models.PositiveIntegerField()),
                ("min_stats_count", models.PositiveIntegerField()),
                ("max_stats_count", models.PositiveIntegerField()),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("money_copper", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "avatar_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.mediaasset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", apps.game.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("level", models.PositiveIntegerField(default=1)),
                ("experience", models.PositiveIntegerField(default=0)),
                ("base_health", models.PositiveIntegerField()),
                ("base_attack", models.PositiveIntegerField()),
                ("base_defense", models.PositiveIntegerField()),
                ("base_critical_chance", models.FloatField()),
                ("base_evasion", models.FloatField()),
                ("power_cached", models.FloatField(blank=True, null=True)),
                ("power_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        db_column="class_key",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.characterclass",
                    ),
                ),
                (
                    "avatar_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game.mediaasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-level", "name"],
            },
        ),
        migrations.CreateModel(
            name="DungeonRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("SUCCESS_WAITING_CLAIM", "Success waiting claim"),
                            ("FAILED_WAITING_CLAIM", "Failed waiting claim"),
                            ("CLAIMED", "Claimed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ends_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("success_chance", models.FloatField()),
                ("is_success", models.BooleanField(blank=True, null=True)),
                (
                    "experience_reward",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "money_reward_copper",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("items_reward", models.JSONField(blank=True, null=True)),
                ("durability_loss", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dungeon_runs",
                        to="game.character",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.dungeonlocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DungeonRunClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_claimed", models.PositiveIntegerField()),
                ("money_claimed_copper", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dungeon_claims",
                        to="game.character",
                    ),
                ),
                (
                    "dungeon_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim",
                        to="game.dungeonrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dungeon_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DungeonLocationItemTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_item_templates",
                        to="game.dungeonlocation",
                    ),
                ),
                (
                    "item_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_locations",
                        to="game.itemtemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="dungeonlocation",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
            ),
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slot", models.CharField(max_length=20)),
                ("item_type", models.CharField(max_length=20)),
                ("rarity", models.CharField(max_length=20)),
                ("item_level", models.PositiveIntegerField()),
                ("stats", models.JSONField(default=dict)),
                ("durability_current", models.PositiveIntegerField()),
                ("durability_max", models.PositiveIntegerField()),
                (
                    "equipped_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipped_items",
                        to="game.character",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="looted_items",
                        to="game.character",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.itemtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RepairTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_copper", models.PositiveIntegerField()),
                ("durability_before", models.PositiveIntegerField()),
                ("durability_after", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_transactions",
                        to="game.useritem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DungeonRunClaimItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_items",
                        to="game.dungeonrunclaim",
                    ),
                ),
                (
                    "user_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_links",
                        to="game.useritem",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="dungeonrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "IN_PROGRESS")),
                fields=("character",),
                name="unique_in_progress_run_per_character",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dungeonlocationitemtemplate",
            unique_together={("location", "item_template")},
        ),
    ]
