# Generated by Django 5.1.4 on 2026-05-17 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_i18n_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={
                "ordering": ["-level", "name"],
                "verbose_name": "Герой",
                "verbose_name_plural": "Герои",
            },
        ),
        migrations.AlterModelOptions(
            name="characterclass",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Класс героя",
                "verbose_name_plural": "Классы героев",
            },
        ),
        migrations.AlterModelOptions(
            name="dungeonlocation",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Локация подземелья",
                "verbose_name_plural": "Локации подземелий",
            },
        ),
        migrations.AlterModelOptions(
            name="dungeonlocationitemtemplate",
            options={
                "verbose_name": "Предмет локации подземелья",
                "verbose_name_plural": "Предметы локаций подземелий",
            },
        ),
        migrations.AlterModelOptions(
            name="dungeonrun",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "Забег в подземелье",
                "verbose_name_plural": "Забеги в подземелья",
            },
        ),
        migrations.AlterModelOptions(
            name="dungeonrunclaim",
            options={
                "verbose_name": "Получение награды",
                "verbose_name_plural": "Получения наград",
            },
        ),
        migrations.AlterModelOptions(
            name="dungeonrunclaimitem",
            options={
                "verbose_name": "Предмет из награды",
                "verbose_name_plural": "Предметы из наград",
            },
        ),
        migrations.AlterModelOptions(
            name="equipmentslotconfig",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Слот экипировки",
                "verbose_name_plural": "Слоты экипировки",
            },
        ),
        migrations.AlterModelOptions(
            name="gameconfig",
            options={
                "verbose_name": "Игровая настройка",
                "verbose_name_plural": "Игровые настройки",
            },
        ),
        migrations.AlterModelOptions(
            name="itemtemplate",
            options={
                "ordering": ["slot", "name"],
                "verbose_name": "Шаблон предмета",
                "verbose_name_plural": "Шаблоны предметов",
            },
        ),
        migrations.AlterModelOptions(
            name="mediaasset",
            options={
                "verbose_name": "Медиа-ассет",
                "verbose_name_plural": "Медиа-ассеты",
            },
        ),
        migrations.AlterModelOptions(
            name="rarityconfig",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Редкость",
                "verbose_name_plural": "Редкости",
            },
        ),
        migrations.AlterModelOptions(
            name="repairtransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Транзакция ремонта",
                "verbose_name_plural": "Транзакции ремонта",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="useritem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Предмет пользователя",
                "verbose_name_plural": "Предметы пользователей",
            },
        ),
        migrations.AlterField(
            model_name="character",
            name="avatar_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_attack",
            field=models.PositiveIntegerField(verbose_name="Базовая атака"),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_critical_chance",
            field=models.FloatField(verbose_name="Базовый шанс критического удара"),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_defense",
            field=models.PositiveIntegerField(verbose_name="Базовая защита"),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_evasion",
            field=models.FloatField(verbose_name="Базовое уклонение"),
        ),
        migrations.AlterField(
            model_name="character",
            name="base_health",
            field=models.PositiveIntegerField(verbose_name="Базовое здоровье"),
        ),
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.ForeignKey(
                db_column="class_key",
                on_delete=django.db.models.deletion.PROTECT,
                to="game.characterclass",
                verbose_name="Класс героя",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="character",
            name="experience",
            field=models.PositiveIntegerField(default=0, verbose_name="Опыт"),
        ),
        migrations.AlterField(
            model_name="character",
            name="level",
            field=models.PositiveIntegerField(default=1, verbose_name="Уровень"),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Имя героя"),
        ),
        migrations.AlterField(
            model_name="character",
            name="power_cached",
            field=models.FloatField(blank=True, null=True, verbose_name="Кэш силы"),
        ),
        migrations.AlterField(
            model_name="character",
            name="power_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата обновления силы"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="character",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="growth_profile",
            field=models.JSONField(verbose_name="Профиль роста"),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="key",
            field=models.SlugField(
                primary_key=True, serialize=False, verbose_name="Ключ класса"
            ),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
                verbose_name="Медиа",
            ),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="name_i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Переводы названия"
            ),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="start_attack",
            field=models.PositiveIntegerField(verbose_name="Стартовая атака"),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="start_critical_chance",
            field=models.FloatField(verbose_name="Стартовый шанс критического удара"),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="start_defense",
            field=models.PositiveIntegerField(verbose_name="Стартовая защита"),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="start_evasion",
            field=models.FloatField(verbose_name="Стартовое уклонение"),
        ),
        migrations.AlterField(
            model_name="characterclass",
            name="start_health",
            field=models.PositiveIntegerField(verbose_name="Стартовое здоровье"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="description_i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Переводы описания"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="duration_seconds",
            field=models.PositiveIntegerField(verbose_name="Длительность в секундах"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="experience_max",
            field=models.PositiveIntegerField(verbose_name="Максимум опыта"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="experience_min",
            field=models.PositiveIntegerField(verbose_name="Минимум опыта"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="item_drop_chance",
            field=models.FloatField(verbose_name="Шанс выпадения предмета"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
                verbose_name="Медиа",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="money_max_copper",
            field=models.PositiveIntegerField(verbose_name="Максимум медных монет"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="money_min_copper",
            field=models.PositiveIntegerField(verbose_name="Минимум медных монет"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="name_i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Переводы названия"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="rarity_chances",
            field=models.JSONField(verbose_name="Шансы редкостей"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="required_power",
            field=models.FloatField(verbose_name="Требуемая сила"),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="dungeonlocationitemtemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="dungeonlocationitemtemplate",
            name="item_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_locations",
                to="game.itemtemplate",
                verbose_name="Шаблон предмета",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonlocationitemtemplate",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_item_templates",
                to="game.dungeonlocation",
                verbose_name="Локация",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonlocationitemtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dungeon_runs",
                to="game.character",
                verbose_name="Герой",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата фактического завершения"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="durability_loss",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Потеря прочности"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="ends_at",
            field=models.DateTimeField(verbose_name="Дата завершения"),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="experience_reward",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Награда опытом"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="is_success",
            field=models.BooleanField(blank=True, null=True, verbose_name="Успешно"),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="items_reward",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Награда предметами"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="game.dungeonlocation",
                verbose_name="Локация",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="money_reward_copper",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Награда в медных монетах"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата старта"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In progress"),
                    ("SUCCESS_WAITING_CLAIM", "Success waiting claim"),
                    ("FAILED_WAITING_CLAIM", "Failed waiting claim"),
                    ("CLAIMED", "Claimed"),
                ],
                default="IN_PROGRESS",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="success_chance",
            field=models.FloatField(verbose_name="Шанс успеха"),
        ),
        migrations.AlterField(
            model_name="dungeonrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaim",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dungeon_claims",
                to="game.character",
                verbose_name="Герой",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaim",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата получения"
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaim",
            name="dungeon_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim",
                to="game.dungeonrun",
                verbose_name="Забег",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaim",
            name="experience_claimed",
            field=models.PositiveIntegerField(verbose_name="Полученный опыт"),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaim",
            name="money_claimed_copper",
            field=models.PositiveIntegerField(verbose_name="Полученные медные монеты"),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaim",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dungeon_claims",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaimitem",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_items",
                to="game.dungeonrunclaim",
                verbose_name="Получение награды",
            ),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaimitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="dungeonrunclaimitem",
            name="user_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_links",
                to="game.useritem",
                verbose_name="Предмет пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentslotconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="equipmentslotconfig",
            name="key",
            field=models.SlugField(
                primary_key=True, serialize=False, verbose_name="Ключ слота"
            ),
        ),
        migrations.AlterField(
            model_name="equipmentslotconfig",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="equipmentslotconfig",
            name="name_i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Переводы названия"
            ),
        ),
        migrations.AlterField(
            model_name="equipmentslotconfig",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="key",
            field=models.SlugField(unique=True, verbose_name="Ключ настройки"),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="gameconfig",
            name="value",
            field=models.JSONField(verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="allowed_classes",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Разрешённые классы"
            ),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("sword", "Sword"),
                    ("dagger", "Dagger"),
                    ("staff", "Staff"),
                    ("bow", "Bow"),
                    ("helmet", "Helmet"),
                    ("armor", "Armor"),
                    ("boots", "Boots"),
                    ("ring", "Ring"),
                ],
                max_length=20,
                verbose_name="Тип предмета",
            ),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="max_durability",
            field=models.PositiveIntegerField(
                default=20, verbose_name="Максимальная прочность"
            ),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
                verbose_name="Медиа",
            ),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="min_durability",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Минимальная прочность"
            ),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="name_i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Переводы названия"
            ),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="possible_stats",
            field=models.JSONField(verbose_name="Возможные характеристики"),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="slot",
            field=models.CharField(
                choices=[
                    ("weapon", "Weapon"),
                    ("helmet", "Helmet"),
                    ("armor", "Armor"),
                    ("boots", "Boots"),
                    ("ring", "Ring"),
                ],
                max_length=20,
                verbose_name="Слот",
            ),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="icon_url",
            field=models.URLField(blank=True, default="", verbose_name="Иконка"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="large_url",
            field=models.URLField(blank=True, default="", verbose_name="Большой URL"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="medium_url",
            field=models.URLField(blank=True, default="", verbose_name="Средний URL"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="original_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Оригинальный URL"
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="small_url",
            field=models.URLField(blank=True, default="", verbose_name="Малый URL"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", verbose_name="Миниатюра"),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="key",
            field=models.SlugField(
                primary_key=True, serialize=False, verbose_name="Ключ редкости"
            ),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="max_item_level",
            field=models.PositiveIntegerField(
                verbose_name="Максимальный уровень предмета"
            ),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="max_stats_count",
            field=models.PositiveIntegerField(verbose_name="Максимум характеристик"),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="min_item_level",
            field=models.PositiveIntegerField(
                verbose_name="Минимальный уровень предмета"
            ),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="min_stats_count",
            field=models.PositiveIntegerField(verbose_name="Минимум характеристик"),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="name",
            field=models.CharField(max_length=80, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="name_i18n",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Переводы названия"
            ),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AlterField(
            model_name="rarityconfig",
            name="stat_multiplier",
            field=models.FloatField(verbose_name="Множитель характеристик"),
        ),
        migrations.AlterField(
            model_name="repairtransaction",
            name="cost_copper",
            field=models.PositiveIntegerField(
                verbose_name="Стоимость в медных монетах"
            ),
        ),
        migrations.AlterField(
            model_name="repairtransaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="repairtransaction",
            name="durability_after",
            field=models.PositiveIntegerField(verbose_name="Прочность после ремонта"),
        ),
        migrations.AlterField(
            model_name="repairtransaction",
            name="durability_before",
            field=models.PositiveIntegerField(verbose_name="Прочность до ремонта"),
        ),
        migrations.AlterField(
            model_name="repairtransaction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repair_transactions",
                to="game.useritem",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="repairtransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repair_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.mediaasset",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Доступ в админку"),
        ),
        migrations.AlterField(
            model_name="user",
            name="money_copper",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Баланс в медных монетах"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="durability_current",
            field=models.PositiveIntegerField(verbose_name="Текущая прочность"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="durability_max",
            field=models.PositiveIntegerField(verbose_name="Максимальная прочность"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="equipped_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipped_items",
                to="game.character",
                verbose_name="Экипирован героем",
            ),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="item_level",
            field=models.PositiveIntegerField(verbose_name="Уровень предмета"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="item_type",
            field=models.CharField(max_length=20, verbose_name="Тип предмета"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="name",
            field=models.CharField(max_length=160, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="owner_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="rarity",
            field=models.CharField(max_length=20, verbose_name="Редкость"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="slot",
            field=models.CharField(max_length=20, verbose_name="Слот"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="source_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="looted_items",
                to="game.character",
                verbose_name="Герой-источник",
            ),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="stats",
            field=models.JSONField(verbose_name="Характеристики"),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="game.itemtemplate",
                verbose_name="Шаблон",
            ),
        ),
        migrations.AlterField(
            model_name="useritem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
