# Generated by Django 5.1.4 on 2026-05-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_character_options_alter_characterclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Название'),
        ),
    ]
