# Generated by Django 5.1.4 on 2026-05-17 07:41

import apps.game.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_mediaasset_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediaasset",
            old_name="icon_url",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="mediaasset",
            old_name="large_url",
            new_name="large",
        ),
        migrations.RenameField(
            model_name="mediaasset",
            old_name="medium_url",
            new_name="medium",
        ),
        migrations.RenameField(
            model_name="mediaasset",
            old_name="original_url",
            new_name="original",
        ),
        migrations.RenameField(
            model_name="mediaasset",
            old_name="small_url",
            new_name="small",
        ),
        migrations.RenameField(
            model_name="mediaasset",
            old_name="thumbnail_url",
            new_name="thumbnail",
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="icon",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="large",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Большой файл",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="medium",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Средний файл",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="original",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Оригинальный файл",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="small",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Малый файл",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Миниатюра",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Название"
            ),
        ),
    ]
