# Generated by Codex on 2026-05-25

import apps.game.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_remove_mediaasset_icon_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("characters", "Персонажи"),
                    ("custom", "Пользовательские"),
                    ("icons", "Иконки"),
                    ("weapons", "Оружие"),
                    ("dungeons", "Данжи"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип",
            ),
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="mediaasset",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="large",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Большой файл 512x512",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="medium",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Средний файл 256x256",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="small",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.game.models.base.media_asset_upload_path,
                verbose_name="Малый файл 128x128",
            ),
        ),
    ]
