# Generated by Codex on 2026-05-27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_mediaasset_asset_type_resize_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="rarityconfig",
            name="economy_multiplier",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name="Множитель экономики"),
        ),
    ]
