# Generated by Django 5.1.4 on 2026-06-04 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_dungeon_mini_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniGameCardFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=64, unique=True, verbose_name="Кодовое обозначение"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Название"
                    ),
                ),
                (
                    "name_i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Переводы названия"
                    ),
                ),
                ("svg_markup", models.TextField(verbose_name="SVG-разметка")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лицо карты мини-игры",
                "verbose_name_plural": "Лица карт мини-игр",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.RemoveField(
            model_name="dungeonlocation",
            name="mini_game_config",
        ),
        migrations.RemoveField(
            model_name="dungeonminigameconfig",
            name="reward_duration_reduction_seconds",
        ),
        migrations.AddField(
            model_name="dungeonminigameattempt",
            name="system_error",
            field=models.BooleanField(
                default=False, verbose_name="Завершено из-за системной ошибки"
            ),
        ),
        migrations.AddField(
            model_name="dungeonminigameconfig",
            name="card_face_codes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Коды лиц карт"
            ),
        ),
        migrations.AddField(
            model_name="dungeonminigameconfig",
            name="max_reduction_seconds",
            field=models.PositiveIntegerField(
                default=600, verbose_name="Абсолютный потолок сокращения в секундах"
            ),
        ),
        migrations.AddField(
            model_name="dungeonminigameconfig",
            name="reward_duration_reduction_percent",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Процент сокращения времени забега",
            ),
        ),
    ]
