# Generated by Django 5.1.4 on 2026-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_health_maxhp_intellect"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonlocation",
            name="hp_loss_fail_percent",
            field=models.FloatField(default=0, verbose_name="Потеря HP при провале, %"),
        ),
        migrations.AddField(
            model_name="dungeonlocation",
            name="hp_loss_success_percent",
            field=models.FloatField(default=0, verbose_name="Потеря HP при успехе, %"),
        ),
        migrations.AddField(
            model_name="dungeonrun",
            name="hp_loss",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Потеря HP"
            ),
        ),
    ]
