# Generated by Django 5.1.4 on 2026-06-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_dungeonlocation_hp_loss_fail_percent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("characters", "Персонажи"),
                    ("custom", "Пользовательские"),
                    ("icons", "Иконки"),
                    ("weapons", "Оружие"),
                    ("dungeons", "Данжи"),
                    ("potion", "Зелья"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="PotionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "name_i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Переводы названия"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "description_i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Переводы описания"
                    ),
                ),
                (
                    "heal_percent",
                    models.PositiveSmallIntegerField(
                        verbose_name="Процент лечения от максимального HP"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="potion_templates",
                        to="game.mediaasset",
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зелье",
                "verbose_name_plural": "Зелья",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="HeroPotionStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potion_storage",
                        to="game.character",
                        verbose_name="Герой",
                    ),
                ),
                (
                    "potion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_entries",
                        to="game.potiontemplate",
                        verbose_name="Зелье",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад зелий героя",
                "verbose_name_plural": "Склады зелий героев",
                "unique_together": {("character", "potion")},
            },
        ),
    ]
