# Generated by Django 5.1.4 on 2026-06-06 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_alter_mediaasset_asset_type_potiontemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonrun",
            name="ingredients_reward",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Награда ингредиентами"
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("characters", "Персонажи"),
                    ("custom", "Пользовательские"),
                    ("icons", "Иконки"),
                    ("weapons", "Оружие"),
                    ("dungeons", "Данжи"),
                    ("potion", "Зелья"),
                    ("ingredient", "Ингредиенты"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="IngredientTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "name_i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Переводы названия"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "description_i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Переводы описания"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basic", "Базовый"),
                            ("regional", "Региональный"),
                            ("rare", "Редкий"),
                        ],
                        default="basic",
                        max_length=16,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredient_templates",
                        to="game.mediaasset",
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="HeroIngredientStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_storage",
                        to="game.character",
                        verbose_name="Герой",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage_entries",
                        to="game.ingredienttemplate",
                        verbose_name="Ингредиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад ингредиентов героя",
                "verbose_name_plural": "Склады ингредиентов героев",
                "unique_together": {("character", "ingredient")},
            },
        ),
        migrations.CreateModel(
            name="DungeonIngredientDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "chance_percent",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Шанс выпадения, %",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Минимум за дроп"
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Максимум за дроп"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_drops",
                        to="game.dungeonlocation",
                        verbose_name="Локация",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dungeon_drops",
                        to="game.ingredienttemplate",
                        verbose_name="Ингредиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дроп ингредиента в локации",
                "verbose_name_plural": "Дропы ингредиентов в локациях",
                "unique_together": {("location", "ingredient")},
            },
        ),
    ]
