# Generated by Django 5.1.4 on 2026-06-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0020_dungeonrun_ingredients_reward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonlocation",
            name="daily_limit",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Дневной лимит заходов (0 = без лимита)"
            ),
        ),
        migrations.AddField(
            model_name="dungeonlocation",
            name="location_type",
            field=models.CharField(
                choices=[("dungeon", "Данж"), ("resource", "Ресурсная локация")],
                db_index=True,
                default="dungeon",
                max_length=16,
                verbose_name="Тип локации",
            ),
        ),
    ]
