# Generated by Django 5.1.4 on 2026-06-06 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0021_dungeonlocation_daily_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CraftRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Код")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("small", "Малая"),
                            ("medium", "Средняя"),
                            ("large", "Большая"),
                        ],
                        max_length=16,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "required_hero_level",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Требуемый уровень героя"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "potion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="game.potiontemplate",
                        verbose_name="Зелье",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт крафта",
                "verbose_name_plural": "Рецепты крафта",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="CraftRecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        verbose_name="Количество на одно зелье"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_links",
                        to="game.ingredienttemplate",
                        verbose_name="Ингредиент",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="game.craftrecipe",
                        verbose_name="Рецепт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент рецепта",
                "verbose_name_plural": "Ингредиенты рецепта",
                "unique_together": {("recipe", "ingredient")},
            },
        ),
    ]
