# Generated by Django 5.1.4 on 2026-06-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0022_craftrecipe_craftrecipeingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "reward_kind",
                    models.CharField(
                        choices=[
                            ("ingredient", "Ингредиент"),
                            ("potion", "Зелье"),
                            ("item", "Предмет"),
                        ],
                        max_length=32,
                        verbose_name="Тип награды",
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[("single", "Одиночная"), ("chest", "Сундук")],
                        max_length=32,
                        verbose_name="Режим выдачи",
                    ),
                ),
                (
                    "name_i18n",
                    models.JSONField(default=dict, verbose_name="Переводы названия"),
                ),
                (
                    "description_i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Переводы описания"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество наград за покупку"
                    ),
                ),
                (
                    "price_money_copper",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена в медных монетах"
                    ),
                ),
                (
                    "price_premium_currency",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена в премиум-валюте"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_offers",
                        to="game.mediaasset",
                        verbose_name="Медиа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение магазина",
                "verbose_name_plural": "Предложения магазина",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShopOfferIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "chance",
                    models.PositiveIntegerField(default=1, verbose_name="Вес шанса"),
                ),
                (
                    "ingredient_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.ingredienttemplate",
                        verbose_name="Шаблон ингредиента",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_entries",
                        to="game.shopoffer",
                        verbose_name="Предложение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент предложения",
                "verbose_name_plural": "Ингредиенты предложения",
            },
        ),
        migrations.CreateModel(
            name="ShopOfferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "chance",
                    models.PositiveIntegerField(default=1, verbose_name="Вес шанса"),
                ),
                (
                    "item_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.itemtemplate",
                        verbose_name="Шаблон предмета",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_entries",
                        to="game.shopoffer",
                        verbose_name="Предложение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет предложения",
                "verbose_name_plural": "Предметы предложения",
            },
        ),
        migrations.CreateModel(
            name="ShopOfferPotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "chance",
                    models.PositiveIntegerField(default=1, verbose_name="Вес шанса"),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potion_entries",
                        to="game.shopoffer",
                        verbose_name="Предложение",
                    ),
                ),
                (
                    "potion_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="game.potiontemplate",
                        verbose_name="Шаблон зелья",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зелье предложения",
                "verbose_name_plural": "Зелья предложения",
            },
        ),
        migrations.CreateModel(
            name="ShopPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "purchase_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Число покупок"
                    ),
                ),
                (
                    "payment_currency",
                    models.CharField(
                        choices=[
                            ("money_copper", "Медные монеты"),
                            ("premium_currency", "Премиум-валюта"),
                        ],
                        max_length=32,
                        verbose_name="Валюта оплаты",
                    ),
                ),
                (
                    "unit_price_snapshot",
                    models.PositiveIntegerField(verbose_name="Снимок цены за единицу"),
                ),
                (
                    "total_price_snapshot",
                    models.PositiveIntegerField(verbose_name="Снимок итоговой цены"),
                ),
                (
                    "reward_kind_snapshot",
                    models.CharField(max_length=32, verbose_name="Снимок типа награды"),
                ),
                (
                    "delivery_mode_snapshot",
                    models.CharField(
                        max_length=32, verbose_name="Снимок режима выдачи"
                    ),
                ),
                (
                    "quantity_snapshot",
                    models.PositiveIntegerField(
                        verbose_name="Снимок количества наград"
                    ),
                ),
                (
                    "result_payload",
                    models.JSONField(default=dict, verbose_name="Результат выдачи"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_purchases",
                        to="game.character",
                        verbose_name="Герой",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="game.shopoffer",
                        verbose_name="Предложение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка в магазине",
                "verbose_name_plural": "Покупки в магазине",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
