# Generated by Django 5.1.4 on 2026-06-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_shopoffer_shopofferingredient_shopofferitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("amount", models.IntegerField(verbose_name="Сумма (со знаком)")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("admin_grant", "Начисление администратором"),
                            ("dungeon_reward", "Награда за подземелье"),
                            ("shop_purchase", "Покупка в магазине"),
                            ("repair", "Ремонт предметов"),
                            ("destroy_refund", "Возврат за уничтожение"),
                            ("exchange_from_premium", "Обмен с премиум-валюты"),
                        ],
                        max_length=64,
                        verbose_name="Причина",
                    ),
                ),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="Баланс после операции"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция медных монет",
                "verbose_name_plural": "Транзакции медных монет",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
