# Generated by Codex on 2026-06-11

import django.db.models.deletion
import django.core.validators
from django.db import migrations, models


def create_default_limit_categories(apps, schema_editor):
    DungeonLimitCategory = apps.get_model("game", "DungeonLimitCategory")
    DungeonLocation = apps.get_model("game", "DungeonLocation")

    dungeon_category, _ = DungeonLimitCategory.objects.update_or_create(
        code="dungeons",
        defaults={
            "name": "Данжи",
            "name_i18n": {"en": "Dungeons", "ru": "Данжи"},
            "limit_count": 0,
            "limit_period_count": 1,
            "limit_period_unit": "day",
            "sort_order": 0,
        },
    )
    resource_category, _ = DungeonLimitCategory.objects.update_or_create(
        code="resources",
        defaults={
            "name": "Ресурсы",
            "name_i18n": {"en": "Resources", "ru": "Ресурсы"},
            "limit_count": 0,
            "limit_period_count": 1,
            "limit_period_unit": "day",
            "sort_order": 10,
        },
    )

    DungeonLocation.objects.filter(location_type="resource").update(limit_category=resource_category)
    DungeonLocation.objects.exclude(location_type="resource").update(limit_category=dungeon_category)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0024_moneytransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DungeonLimitCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("code", models.SlugField(max_length=64, unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("name_i18n", models.JSONField(blank=True, default=dict, verbose_name="Переводы названия")),
                ("limit_count", models.PositiveIntegerField(default=0, verbose_name="Лимит стартов (0 = без лимита)")),
                (
                    "limit_period_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество единиц периода",
                    ),
                ),
                (
                    "limit_period_unit",
                    models.CharField(
                        choices=[("hour", "Час"), ("day", "День"), ("week", "Неделя"), ("month", "Месяц")],
                        default="day",
                        max_length=16,
                        verbose_name="Единица периода",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки")),
            ],
            options={
                "verbose_name": "Категория лимита локаций",
                "verbose_name_plural": "Категории лимитов локаций",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="dungeonlocation",
            name="limit_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="game.dungeonlimitcategory",
                verbose_name="Категория лимита",
            ),
        ),
        migrations.RunPython(create_default_limit_categories, noop_reverse),
        migrations.AlterField(
            model_name="dungeonlocation",
            name="limit_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="game.dungeonlimitcategory",
                verbose_name="Категория лимита",
            ),
        ),
    ]
