# Generated by Django 5.1.4 on 2026-06-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0025_dungeon_limit_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("characters", "Персонажи"),
                    ("custom", "Пользовательские"),
                    ("icons", "Иконки"),
                    ("weapons", "Оружие"),
                    ("dungeons", "Данжи"),
                    ("potion", "Зелья"),
                    ("ingredient", "Ингредиенты"),
                    ("chests", "Сундуки"),
                    ("map", "Карта"),
                    ("bosses", "Боссы"),
                    ("scrolls", "Свитки"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип",
            ),
        ),
    ]
