# Generated by Django 5.1.4 on 2026-06-15 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0026_alter_mediaasset_asset_type_add_chests_map_bosses_scrolls"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryTaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("task_name", models.CharField(max_length=255, verbose_name="Задача")),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID задачи Celery"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dispatched", "Отправлена"),
                            ("success", "Успешно"),
                            ("failure", "Ошибка"),
                        ],
                        default="dispatched",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("result", models.TextField(blank=True, verbose_name="Результат")),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="celery_task_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Запущена пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог задачи",
                "verbose_name_plural": "Логи задач",
                "ordering": ("-created_at",),
            },
        ),
    ]
