# Generated by Codex on 2026-06-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0027_celery_task_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoDungeonRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("STOPPING", "Stopping"),
                            ("STOPPED", "Stopped"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "stop_reason_code",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Код причины остановки"),
                ),
                (
                    "stop_reason_message",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Причина остановки"),
                ),
                (
                    "stop_reason_details",
                    models.JSONField(blank=True, default=dict, verbose_name="Детали причины остановки"),
                ),
                (
                    "summary_unread",
                    models.BooleanField(db_index=True, default=False, verbose_name="Сводка не прочитана"),
                ),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата запуска"),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата остановки"),
                ),
                (
                    "runs_claimed",
                    models.PositiveIntegerField(default=0, verbose_name="Учтено походов"),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="Успешных походов"),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(default=0, verbose_name="Проваленных походов"),
                ),
                (
                    "experience_total",
                    models.PositiveIntegerField(default=0, verbose_name="Всего опыта"),
                ),
                (
                    "money_total_copper",
                    models.PositiveIntegerField(default=0, verbose_name="Всего меди"),
                ),
                (
                    "items_total",
                    models.PositiveIntegerField(default=0, verbose_name="Всего предметов"),
                ),
                (
                    "ingredients_total",
                    models.PositiveIntegerField(default=0, verbose_name="Всего ингредиентов"),
                ),
                (
                    "current_hp",
                    models.PositiveIntegerField(default=0, verbose_name="Текущее HP"),
                ),
                (
                    "max_hp",
                    models.PositiveIntegerField(default=0, verbose_name="Максимальное HP"),
                ),
                (
                    "durability_loss_total",
                    models.PositiveIntegerField(default=0, verbose_name="Общая потеря прочности"),
                ),
                (
                    "durability_changes",
                    models.JSONField(blank=True, default=list, verbose_name="Изменения прочности"),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Сводка"),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_dungeon_runs",
                        to="game.character",
                        verbose_name="Герой",
                    ),
                ),
                (
                    "current_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auto_run_current_for",
                        to="game.dungeonrun",
                        verbose_name="Текущий поход",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auto_runs",
                        to="game.dungeonlocation",
                        verbose_name="Локация",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_dungeon_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автозапуск",
                "verbose_name_plural": "Автозапуски",
            },
        ),
        migrations.CreateModel(
            name="AutoDungeonRunClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("is_success", models.BooleanField(default=False, verbose_name="Успешный поход")),
                ("experience", models.PositiveIntegerField(default=0, verbose_name="Опыт")),
                ("money_copper", models.PositiveIntegerField(default=0, verbose_name="Медь")),
                ("items_count", models.PositiveIntegerField(default=0, verbose_name="Количество предметов")),
                ("ingredients_count", models.PositiveIntegerField(default=0, verbose_name="Количество ингредиентов")),
                ("current_hp", models.PositiveIntegerField(default=0, verbose_name="Текущее HP")),
                ("max_hp", models.PositiveIntegerField(default=0, verbose_name="Максимальное HP")),
                ("durability_loss", models.PositiveIntegerField(default=0, verbose_name="Потеря прочности")),
                (
                    "items_preview",
                    models.JSONField(blank=True, default=list, verbose_name="Превью предметов"),
                ),
                (
                    "ingredients_preview",
                    models.JSONField(blank=True, default=list, verbose_name="Превью ингредиентов"),
                ),
                (
                    "durability_changes",
                    models.JSONField(blank=True, default=list, verbose_name="Изменения прочности"),
                ),
                (
                    "counted_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата учета"),
                ),
                (
                    "auto_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_claims",
                        to="game.autodungeonrun",
                        verbose_name="Автозапуск",
                    ),
                ),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_run_claim",
                        to="game.dungeonrunclaim",
                        verbose_name="Получение награды",
                    ),
                ),
                (
                    "dungeon_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_run_claim",
                        to="game.dungeonrun",
                        verbose_name="Поход в данж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда автозапуска",
                "verbose_name_plural": "Награды автозапусков",
            },
        ),
        migrations.AddConstraint(
            model_name="autodungeonrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "STOPPING"])),
                fields=("character",),
                name="one_active_auto_dungeon_run_per_character",
            ),
        ),
        migrations.AddConstraint(
            model_name="autodungeonrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "STOPPED"), ("summary_unread", True)),
                fields=("character",),
                name="one_unread_auto_dungeon_run_summary_per_character",
            ),
        ),
    ]
